# Site settings
title: Seeking attention
description: "John Haynes, product and service designer"
author:
  name: "John Haynes"
  email: "mail@johnhayn.es"

# Build settings
baseurl: "/"
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false

# Sitemap
url: "https://johnhayn.es" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# search config
# var sjs = SimpleJekyllSearch({
#   searchInput: document.getElementById('search-input'),
#   resultsContainer: document.getElementById('results-container'),
#   json: '/search.json'
# })