# site settings
title: John Haynes
subtitle: Product & service design
email: mail@johnhayn.es
description: The blog of Product Designer John Haynes
logo: '/assets/images/logo.svg'
github: [metadata]

# Contact Details
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 
facebook_url: 
instagram_url: 
youtube_url: 

# Action Buttons
actions:  
  # - label: 'Book'
  #   url: '/book'
  # - label: 'Test'
  #   url:  '/test' 
  # - label: 'Test2'
  #   url:  '/test2' 

# Formspree

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 5

# sitemap

# config
setup: blog # airtable or blog; controls the section on the home page and other parts of the site
repository: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://johnhayn.es # the base hostname & protocol for your site
permalink: /:title/
future: true
markdown: kramdown
sass:
  style: compressed